# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('travel_from', models.DateField()),
                ('travel_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_users', models.ManyToManyField(related_name='joint_trips', to='belt_test.User')),
            ],
        ),
    ]
