# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_test', '0002_travel_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_plan',
            old_name='travel_to',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='travel_plan',
            old_name='travel_from',
            new_name='start_date',
        ),
    ]
