# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_test', '0003_auto_20170927_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_plan',
            name='planned_by',
            field=models.CharField(default='Pat', max_length=255),
            preserve_default=False,
        ),
    ]
