# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_test', '0004_travel_plan_planned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_plan',
            name='planned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_trips', to='belt_test.User'),
        ),
    ]
